name: Generate list

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '01 01 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Generate file
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |-
        python generate.py > generated.md
    - name: Commit and push to generated
      run: |-
        git config --global user.email "workflow-bot@example.com"
        git config --global user.name "workflow-bot"
        git checkout --orphan generated
        git rm --cached -r .
        git add generated.md
        git commit -m "generate list"
        git push --set-upstream origin generated --force
